{% set name = "libcds" %}
{% set version = "0.1.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/cr_tools/libcds/-/archive/{{ version }}/{{ version }}.tar.gz
  sha256: 2f775e2eee3d3014868b18438dce5af941c7ddc83b20d21406fc98b081426ba9

build:
  skip: true  # [win or osx]
  error_overlinking: true
  error_overdepending: true
  number: 0
  run_exports:
    - {{ pin_subpackage('libcds', max_pin='x.x') }}

requirements:
  build:
   - {{ compiler('c') }}
   - {{ stdlib("c") }}
   - cmake
   - make  # [not win]
   - pkg-config  # [not win]

  host:
   - glib

test:
  commands:
    - test -f ${PREFIX}/lib/libcds${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/cds/cdstime.h  # [unix]  
    - if not exist %LIBRARY_INC%\cds\cdstime.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cds.dll exit 1  # [win]
     
about:
  home: https://git.ligo.org/cds/software/cr_tools/libcds
  dev_url: https://git.ligo.org/cds/software/cr_tools/libcds.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: Library for advinced LIGO frequency domain diagnostics tool

extra:
  recipe-maintainers:
    - evonreis
